### ISSUE TITLE
Unable to read documents from encrypted store 

### ISSUE THREAD

**Issue by canapa** [Acosix/alfresco-simple-content-stores#21]
Hi,
I’d like to use an encrypted content store to save all the files of an Alfresco site. So I have used this configuration:

```
simpleContentStores.enabled=true
simpleContentStores.customStores=klSiteRoutingStore,klEncryptedFileStore,klCustomFileStore,defaultTenantFileContentStore
simpleContentStores.rootStore=klSiteRoutingStore

simpleContentStores.customStore.klCustomFileStore.type=standardFileStore
simpleContentStores.customStore.klCustomFileStore.value.rootDirectory=${dir.root}/klContentStore
simpleContentStores.customStore.klCustomFileStore.value.deleteEmptyDirs=true
simpleContentStores.customStore.klCustomFileStore.value.fixedLimit=1073741824

simpleContentStores.customStore.klEncryptedFileStore.type=encryptingFacadeStore
simpleContentStores.customStore.klEncryptedFileStore.ref.backingStore=klCustomFileStore
simpleContentStores.customStore.klEncryptedFileStore.value.keyStorePath=${dir.root}/keystore/klAlfresco.jks
simpleContentStores.customStore.klEncryptedFileStore.value.keyStorePassword=password
simpleContentStores.customStore.klEncryptedFileStore.value.masterKeyAlias=alfcontentstorekey
simpleContentStores.customStore.klEncryptedFileStore.value.masterKeyPassword=password
simpleContentStores.customStore.klEncryptedFileStore.value.keyAlgorithm=RSA
simpleContentStores.customStore.klEncryptedFileStore.value.masterKeyStoreId=klContentStoreKeyId

simpleContentStores.customStore.klSiteRoutingStore.type=siteRoutingStore
simpleContentStores.customStore.klSiteRoutingStore.ref.fallbackStore=defaultTenantFileContentStore
simpleContentStores.customStore.klSiteRoutingStore.map.storeBySitePreset.ref.encrypted-site=klEncryptedFileStore
```

When I upload a pdf document, it is written encrypted as expected. But after that, it can’t be read any more: no thumbnails was created, no preview is available and if I download the document it is unreadable because I obtain the encrypted version.

I’m using an Alfresco Community Edition 5.1 (201605) so I’ve installed the alfresco-5.0 branch.

Could you help me?

**Comment by AFaust** [comment]
I hope to have some time this weekend to look at this. I have to update this project to the most current Alfresco versions anyway at  some point, and have just put off any work on the project as most of my time was consumed by customer projects the first half of this year.

**Comment by AFaust** [comment]
Looks like the error seems to be related to a cache design error in Alfresco. The symmetric encryption key is not stored for the newly created content, so upon read it cannot be decrypted transparently. The low-level issue is caused by the following pattern upon writing the content:

- we do a lookup if a ContentUrlEntity already exists in the database - this causes a DB lookup and if no entity exists, Alfresco will put a "value not found" dummy value in the cache to avoid another lookup
- if no ContentUrlEntity exists, we (indirectly) create one by creating a ContentDataEntity (there is no API to directly create a ContentUrlEntity) - this does NOT remove the "value not found" dummy in the ContentUrlEntity cache
- we attempt to store the encryption key and associate that with the ContentUrlEntity - Alfresco's DAO implementation skips that step as it believes the ContentUrlEntity does not exists ("value not found" dummy in the cache)

**Comment by AFaust** [comment]
I have adapted the usage of Alfresco ContentDAO APIs in the master and alfresco-5.0 branch (even though master branch did not seem affected, i.e. behaviour of Alfresco is slightly different). I still ahve to apply the change to the alfresco-4.2 branch, but you can already retest in Alfresco 5.1.
Please be aware there has been a slight change in the dependency to my utility addon, which has been simplified (no longer requires the "full" addon, only the "core" components of it, which are less invasive, e.g. do not include functional patches).

**Comment by canapa** [comment]
Hello Axel,
  thanks for your feedback and for your quick fix.

  Now it works! Great job! 

  Thank you very much.

  Kind Regards.
