### ISSUE TITLE
EncryptingContentStore: Revoke and change master key

### ISSUE THREAD

**Issue by nschwalbe** [Acosix/alfresco-simple-content-stores#34]
Hello Axel,

thanks for this very helpful Alfresco Addon!
We want to use the encryption module and setup was easy, but I wonder if it is possible to revoke and change the master key if it is necessary? All the symmetric keys needs to be re-encrypted with the new master key. Do you have some kind of script or action for that?

Best regards,
Nathanael

**Comment by AFaust** [comment]
Hi Nathanael,

you might be happy to hear that this is exactly what I have been working on the last week and am currently running local tests (not yet finalised / pushed in this public repository). You might have seen the last commit ~11 days ago which referred to encryption improvements in the next dev cycle. I have a customer who asked me to specifically handle key rotation / re-encryption so that the encrypted content store essentially has near parity with the Alfresco's Enterprise functionality. The refactorings for 1.2.0-SNAPSHOT include

- support multiple active master keys
- support multiple key stores as sources
- pick a random active master key for each symmetric one
- consolidate key handling (key config no longer per-store)
- support (secure) symmetric keys (e.g. AES) as master keys
- support decryption only master keys (e.g. private key without public one) for historic, not yet re-encrypted symmetric keys
- validation at startup against database
- validation at startup against potential cluster nodes, e.g. to support Enterprise and/or [aldica](https://github.com/aldica/aldica) users)
- plugin for the [OOTBee Support Tools Command Console](https://github.com/OrderOfTheBee/ootbee-support-tools/wiki/Command%20Console) to support administrative actions, like enable/disable keys, and trigger re-encryption

**Comment by nschwalbe** [comment]
That sounds great! So I will watch this repository to get notified when you release the new features. :+1:

**Comment by nschwalbe** [comment]
Hi Axel,

are you planning to build a 1.4.0 release version or do you still work on tests etc?

**Comment by AFaust** [comment]
@nschwalbe I am mostly waiting on test feedback from the customer who ordered the feature extension. My tests are all done and fine, but since the customer already has a substantial set of existing content, their upgrade test + feedback may still uncover corner-cases I was not able to reproduce or even consider in my tests. Unfortunately, they indicated that they were busy with other topics at the moment - I actually started ealier on the implementation than originally planned, as I had some unscheduled project delays.

**Comment by nschwalbe** [comment]
Ok, thanks for your quick response! It is good to hear that the feature extension will be solid tested.
